### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by Herbert0305** [Fenglei104/DeepPROTACs#11]
This is a very interesting job. When I tried to run single_predict.py, I reported the following error: “AttributeError: 'GCNConv' object has no attribute 'explain'”. How can I solve this problem? thank you! Have you defined explain in the code?

**Comment by Herbert0305** [comment]
Traceback (most recent call last):
  File "D:\Protac\DeepPROTACs-master\single_prediction.py", line 216, in <module>
    data_sample['smiles_length'],)
  File "D:\Anaconda3\envs\DeepPROTACs\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Protac\DeepPROTACs-master\model.py", line 71, in forward
    v_0 = self.ligase_ligand_model(ligase_ligand)
  File "D:\Anaconda3\envs\DeepPROTACs\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Protac\DeepPROTACs-master\model.py", line 18, in forward
    x = self.gcn1(x, edge_index, edge_attr)
  File "D:\Anaconda3\envs\DeepPROTACs\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Anaconda3\envs\DeepPROTACs\lib\site-packages\torch_geometric\nn\conv\gcn_conv.py", line 233, in forward
    size=None)
  File "D:\Anaconda3\envs\DeepPROTACs\lib\site-packages\torch_geometric\nn\conv\message_passing.py", line 415, in propagate
    decomposed_layers = 1 if self.explain else self.decomposed_layers
  File "D:\Anaconda3\envs\DeepPROTACs\lib\site-packages\torch\nn\modules\module.py", line 1270, in __getattr__
    type(self).__name__, name))
AttributeError: 'GCNConv' object has no attribute 'explain'

This is the complete error reporting interface.

**Comment by Fenglei104** [comment]
Please see https://github.com/Fenglei104/DeepPROTACs/issues/9#issuecomment-1473532156
Thanks

**Comment by Herbert0305** [comment]
Thank you for your answer, the above problem has been solved. Another problem is that I downloaded the protac,linker,warhead,e3_ligand file from protacdb, but the file did not indicate which linker,warhead and e3_ligand the protac is composed of. May I ask how do you deal with this problem?

**Comment by Fenglei104** [comment]
> Thank you for your answer, the above problem has been solved. Another problem is that I downloaded the protac,linker,warhead,e3_ligand file from protacdb, but the file did not indicate which linker,warhead and e3_ligand the protac is composed of. May I ask how do you deal with this problem?

Each page in PROTAC-DB contains the information. We collected them from the website.

**Comment by Herbert0305** [comment]
Thank you for your answer.
May I ask how you got the data in protacs_example.csv file? I downloaded the protacs.csv file in PROTACDB (it contains all the protac in PROTACDB), but a lot of data in the file was missing. For example, Degradation activity, Degradation Identification new 1, Degradation Identification and other data cannot be found. How did you get these data and fill them up? If possible, could you please share with me the method of obtaining and filling your data? Thank you.
Also, I'd like to know how you tagged protac and generated label.pt.
