### ISSUE TITLE
Error when run the main.py

### ISSUE THREAD

**Issue by lh12565** [Fenglei104/DeepPROTACs#4]
Hi, I install the DeepPROTACs via 'conda env create -f env.yaml', but there is an error when I run python main.py:
```
RuntimeError: 
Tried to access nonexistent attribute or method 'crow_indices' of type 'Tensor'.:
  File "/NAS/lh/software/miniconda3/envs/DeepPROTACs/lib/python3.7/site-packages/torch_sparse/tensor.py", line 109
    def from_torch_sparse_csr_tensor(self, mat: torch.Tensor,
                                     has_value: bool = True):
        rowptr = mat.crow_indices()
                 ~~~~~~~~~~~~~~~~ <--- HERE
        col = mat.col_indices()
```
I downgraded torch-sparse from 0.6.14 to 0.6.12 as [here](https://github.com/snap-stanford/GraphGym/issues/43) said, but there is another error as below:
```
ImportError: dlopen: cannot load any more object with static TLS
___________________________________________________________________________
Contents of /NAS/lh/software/miniconda3/envs/DeepPROTACs/lib/python3.7/site-packages/sklearn/__check_build:
__pycache__               __init__.py               _check_build.cpython-37m-x86_64-linux-gnu.so
setup.py
___________________________________________________________________________
It seems that scikit-learn has not been built correctly.

If you have installed scikit-learn from source, please do not forget
to build the package before using it: run `python setup.py install` or
`make` in the source directory.

If you have used an installer, please check that it is suited for your
Python version, your operating system and your platform.
```
My system is centos7. I don't know how to solve it?
Thanks!

**Comment by Fenglei104** [comment]
hello, there! It seems that your scikit-learn has some problem. Maybe you can re-install it?

**Comment by miderxi** [comment]
Traceback (most recent call last):
  File "/home/v/proj/DeepPROTACs/main.py", line 85, in <module>
    main()
  File "/home/v/proj/DeepPROTACs/main.py", line 70, in main
    model = train(
  File "/home/v/proj/DeepPROTACs/train_and_test.py", line 38, in train
    _ = valids(model, valid_loader, device)
  File "/home/v/proj/DeepPROTACs/train_and_test.py", line 32, in valids
    return sum(loss)/iteration, accuracy_score(y_true, y_pred), roc_auc_score(y_true, y_score)
  File "/home/v/micromamba/envs/test2/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
  File "/home/v/micromamba/envs/test2/lib/python3.10/site-packages/sklearn/metrics/_ranking.py", line 640, in roc_auc_score
    return _average_binary_score(
  File "/home/v/micromamba/envs/test2/lib/python3.10/site-packages/sklearn/metrics/_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "/home/v/micromamba/envs/test2/lib/python3.10/site-packages/sklearn/metrics/_ranking.py", line 382, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
